// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    /**
     * IsObsidian bool   `json:"isObsidian"`
     * VaultPath  string `json:"vaultPath"`
     */
    "isVimModeEnabled": boolean;
    "inboxPath": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("isVimModeEnabled" in $$source)) {
            this["isVimModeEnabled"] = false;
        }
        if (!("inboxPath" in $$source)) {
            this["inboxPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}
