// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3259914990).then(($result: any) => {
        return $$createType0($result);
    });
}

export function InboxPath(): $CancellablePromise<string> {
    return $Call.ByID(2273021689);
}

export function Save(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(3879638799, settings);
}

export function ToggleVimMode(): $CancellablePromise<boolean> {
    return $Call.ByID(4158284469);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
